config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'
  get 'messages/create'
  get 'chats/create'
  get 'chats/show'
  get 'moods/index'
  get 'moods/create'
  devise_for :users
  root to: "pages#home"
  resources :menu_items, only: [:show, :index]
  resources :beverages, only: [:show, :index]
  resources :wines, only: [:show, :index]
  resources :order_items
  resources :moods, only: [:index]

  resources :chats, only: [:create, :show] do
    resources :messages, only: [:index, :create]
  end

  post "chats/:id/add_recommendations",
       to: "chats#add_recommendations",
       as: :add_recommendations

  resources :order_items

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"




end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  has_many :order_items
  has_neighbors :embedding
  after_create :set_embedding

  validates :name, presence: true
  validates :description, length: { maximum: 300 }
  validates :price, presence: true, numericality: { greater_than: 0 }


  def index
  end

  private

  def set_embedding
    embedding = RubyLLM.embed("Dish: #{name}. #{description}. #{price}")
    update(embedding: embedding.vectors)
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  def index
    @menu_items = MenuItem.all
  end

  def show
    @menu_item = MenuItem.find(params[:id])
  end
end

app/views/menu_items/index.html.erb
<div class="d-flex justify-content-center align-items-start vh-100 bg-dark pt-1">
  <div class="floating-card" style="width: 100%;" >


        <h1 class="display-5 mb-3 heading-gold">Menu</h1>

        <table class="table table-hover table-dark align-middle">
          <thead class="table-dark">
          </thead>

          <tbody>
            <% @menu_items.each_with_index do |menu_item, index| %>
              <tr>
                <td class="fw-semibold"><%= menu_item.name %></td>
                <td>€ <%= number_with_precision(menu_item.price, precision: 2) %></td>
                <td class="text-end">
                  <%= link_to "Details", menu_item_path(menu_item), class: "btn btn-gold btn-sm" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
  </div>
</div>

app/views/menu_items/show.html.erb
<div class="d-flex justify-content-center align-items-start bg-dark vh-100 pt-1 ">
  <div class="floating-card" style="width: 100%;" >

    <div class="row g-4 align-items-center">

      <!-- LEFT SIDE: TEXT -->
      <div class="col-md-8">

        <div class="card-body">
          <h2 class="fw-bold mb-3 text-center text-uppercase heading-gold">
          <%= @menu_item.name %>
          </h2>
          <p class="lead">
          <%= @menu_item.description.presence || "No description available." %>
          </p>
          <p class="fs-5 fw-semibold mb-3">€ <%= @menu_item.price %></p>
        </div>

      </div>

      <!-- RIGHT SIDE: IMAGE -->
        <div class="col-md-4 text-center">
          <% if @menu_item.image_name.present? %>
            <%= image_tag asset_path(@menu_item.image_name),
                class: "rounded-3 shadow",
                style: "max-height: 180px; width: 100%; height: auto; object-fit: contain;",
                alt: @menu_item.name %>
          <% else %>
            <p class="text-muted">No image available</p>
          <% end %>
        </div>

      <!-- BUTTONS -->
      <div class="mt-4 d-flex justify-content-between">
          <%= link_to "Back to Menu", menu_items_path, class: "btn btn-gold" %>
          <%= button_to "Add to Order",
            order_items_path(order_item: { menu_item_id: @menu_item.id, quantity: 1 }),
            method: :post,
            class: "btn btn-gold" %>
      </div>



    </div>
  </div>
</div>