config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'
  get 'messages/create'
  get 'chats/create'
  get 'chats/show'
  get 'moods/index'
  get 'moods/create'
  devise_for :users
  root to: "pages#home"
  resources :menu_items, only: [:show, :index]
  resources :beverages, only: [:show, :index]
  resources :wines, only: [:show, :index]
  resources :order_items
  resources :moods, only: [:index]

  resources :chats, only: [:create, :show] do
    resources :messages, only: [:index, :create]
  end

  post "chats/:id/add_recommendations",
       to: "chats#add_recommendations",
       as: :add_recommendations

  resources :order_items

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"




end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark border-top shadow-sm">
  <div class="container-fluid">

    <!-- Toggle button (hamburger) -->
    <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#mainNavbar" aria-controls="mainNavbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Collapsible content -->
    <div class="collapse navbar-collapse justify-content-center" id="mainNavbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link px-3" %>
        </li>
        <li class="nav-item">
          <%= link_to "Menu", menu_items_path, class: "nav-link px-3" %>
        </li>
        <li class="nav-item">
          <%= link_to "Wines", wines_path, class: "nav-link px-3" %>
        </li>
        <li class="nav-item">
          <%= link_to "Drinks", beverages_path, class: "nav-link px-3" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Order", order_items_path, class: "nav-link px-3" %>
        </li>
      </ul>
    </div>
  </div>
</nav>